// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRub71c71ESkqFDiFPbcBhwuDc31bB_pA',
    appId: '1:219848903601:web:fcf7fddac8ff55e94d0b90',
    messagingSenderId: '219848903601',
    projectId: 'ecommerce-f875c',
    authDomain: 'ecommerce-f875c.firebaseapp.com',
    storageBucket: 'ecommerce-f875c.appspot.com',
    measurementId: 'G-8CXGK0L03W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nTMhAY69l7Z_f1039Br3bZuZ_ti0juI',
    appId: '1:219848903601:android:2b0ca24bd4e0c1e84d0b90',
    messagingSenderId: '219848903601',
    projectId: 'ecommerce-f875c',
    storageBucket: 'ecommerce-f875c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfS07bzCdPToT6Sf11_HjToiKsD4Fw7mI',
    appId: '1:219848903601:ios:686217699e60a0d34d0b90',
    messagingSenderId: '219848903601',
    projectId: 'ecommerce-f875c',
    storageBucket: 'ecommerce-f875c.appspot.com',
    iosClientId: '219848903601-ado75t20jlf28g5tub2gfus6piovtijs.apps.googleusercontent.com',
    iosBundleId: 'com.wasem.sezonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfS07bzCdPToT6Sf11_HjToiKsD4Fw7mI',
    appId: '1:219848903601:ios:ffbd35209497efff4d0b90',
    messagingSenderId: '219848903601',
    projectId: 'ecommerce-f875c',
    storageBucket: 'ecommerce-f875c.appspot.com',
    iosClientId: '219848903601-95jufb76jvk76vure40hpl9cs7qla7dn.apps.googleusercontent.com',
    iosBundleId: 'com.wasem.sezonApp.RunnerTests',
  );
}
